### ISSUE TITLE
Fix the validation error while also avoiding: "'instance' is not a valid sequence index"

### ISSUE THREAD

**Issue by rohan-uiuc** [hinthornw/trustcall#8]
I've been using trustcall and found it quite useful for structured extraction. I am trying to generate a schema of properties from large pdf documents based on my prompt and trying to update it by passing in batches of chunks. 

I am running into this error once the update stage is hit, model often tries to update the json at path `instance`. On looking further it seems this field is used internally to track instances of schema. 

Here are 2 langsmith traces with errors:
https://smith.langchain.com/public/e3145f19-9d29-4ce1-9cff-3bebe558d55f/r
https://smith.langchain.com/public/0ae5acff-0e70-4f11-9baa-ebfb25af207d/r

Not sure how to fix it, appreciate all the help.

**Comment by hinthornw** [comment]
Thank you for reporting! Sorry for the delay was celebrating a big life event - will try to investigate this now that I'm back

**Comment by rohan-uiuc** [comment]
I was able to resolve this issue by fixing my initial implementation from `"existing": {initial_user.model_dump()}` to `"existing": {"User": initial_user.model_dump()}`, as mentioned in the Readme. 
Thanks for building this, it works like a charm!
